version: '3.9'
services: 
  node:
    container_name: build-out-new
    build: .
    volumes: 
      - ./build:/app/out

  nginx:
    image: nginx:latest
    volumes: 
     - ./build/:/usr/share/nginx/html/test
    depends_on: 
      - node
    ports: 
      - 5731:80
